Repository Orange-OpenSource/IOT-Map-Component, pull requests merged in 2024-02, with the labels that each got.

#135 Dependencies: use local version on example project
  angular.json
  package-lock.json
  package.json
  src/map/map.component.html
Labels: enhancement, tests

#136 fix(storybook): build process
  package.json
Labels: storybook, fix

#139 chore(deps-dev): bump Node from 12.x to 14.x in `Docs` workflow
  .github/workflows/docs.yml
Labels: dependencies, chore

#150 chore(deps): bump Angular to 17 in `test/angular` project
  test/angular/angular.json
  test/angular/package-lock.json
  test/angular/package.json
Labels: dependencies, chore, tests

#151 chore(deps): bump Storybook from 6.4.9 to 7.6.15
  .github/workflows/docs.yml
  .nvmrc
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/iotMapManager/.gitignore
  src/iotMapManager/.nvmrc
  src/iotMapManager/dist/index.js
  src/stories/Clusters.stories.js
  src/stories/Gauge.stories.js
  src/stories/GaugeWithInner.stories.js
  src/stories/Inner.stories.js
  src/stories/Shapes.stories.js
  src/stories/Test.stories.const.ts
  src/stories/Test.stories.ts
  src/stories/UserMarker.stories.js
  src/stories/data.const.js
  src/stories/stories.css
Labels: documentation, dependencies, chore

#152 chore(lib): migrate from Node 14 to 20
  package.json
  src/iotMapManager/.gitignore
  src/iotMapManager/.nvmrc
  src/iotMapManager/dist/index.js
  src/iotMapManager/package-lock.json
Labels: dependencies, chore

#156 chore: change `master` reference to `main`
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/docs.yml
  README.md
  src/iotMapManager/css/map.css
  src/iotMapManager/css/markers.css
  src/iotMapManager/css/popup.css
  src/iotMapManager/css/shadows.css
  src/iotMapManager/css/tabs.css
  src/iotMapManager/import_png.d.ts
  src/iotMapManager/index.ts
  src/iotMapManager/iot-map-manager.css
  src/iotMapManager/src/iot-map-area-manager.ts
  src/iotMapManager/src/iot-map-area.ts
  src/iotMapManager/src/iot-map-cluster-manager.ts
  src/iotMapManager/src/iot-map-cluster.ts
  src/iotMapManager/src/iot-map-common-svg.ts
  src/iotMapManager/src/iot-map-config.ts
  src/iotMapManager/src/iot-map-icons.ts
  src/iotMapManager/src/iot-map-manager.ts
  src/iotMapManager/src/iot-map-marker-manager.ts
  src/iotMapManager/src/iot-map-marker.ts
  src/iotMapManager/src/iot-map-path-manager.ts
  src/iotMapManager/src/iot-map-path.ts
  src/iotMapManager/src/iot-map-types.ts
  src/iotMapManager/src/iot-map-user-marker-manager.ts
  src/iotMapManager/src/iot-map-user-marker.ts
Labels: chore
